name: gozen_boarding_pro
description: Gozen Boarding Pro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.4
  share_plus: ^10.0.3

  # Camera/Barcode (BCBP)
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/company_logo.png