name: gozen_boarding_pro
description: Gozen Boarding Pro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.3
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  path_provider: ^2.1.4
  share_plus: ^10.1.4

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  excel: ^2.1.0
  universal_html: ^2.2.7
  universal_io: ^2.3.0

  # OCR
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/company_logo.png
